"""
FOR CONSTANT DEFINES IN JCP HTML PARSING
"""
NUM_AUTHORS = 10
NUM_KEYWORDS = 12
TAG_A = "a"
TAG_DIV = "div"
TAG_H3 = "h3"
TAG_LI = "li"
TAG_UL = "ul"
TITLE_ISSUE_INFORMATION = "Issue Information"
TITLE_RESEARCH_REVIEW = "Research Review"
TITLE_RESEARCH_REVIEWS = "Research Reviews"
TITLE_RESEARCH_DIALOGUE = "Research Dialogue"
TITLE_RESEARCH_DIALOGUES = "Research Dialogues"
CLASS_VOLUME_ISSUE = "cover-image__parent-item"
CLASS_COVER_IMAGE_DATE = "cover-image__date"
CLASS_PAGE_RANGE = "page-range"
CLASS_EPUB_DATE = "ePubDate"
CLASS_TIME_UL = "rlist--inline separator issue-item__details"
CLASS_ISSUE_ITEMS_CONTAINER = "issue-items-container bulkDownloadWrapper"
CLASS_AUTHORS = "loa comma loa-authors-trunc"
CLASS_ISSUE_ITEMS_H3 = "toc__heading section__header to-section"
CLASS_ISSUE_ITEM = "issue-item"
CLASS_PAPER_TITLE = "issue-item__title visitable"
CLASS_ITEM_LINKS = "rlist--inline separator issue-item__links"
